### ISSUE TITLE
Re-enable publishing to open-vsx

### ISSUE THREAD

**Issue by shati-patel** [github/vscode-codeql#1085]
We currently depend on the https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer extension.

That extension still works, but is deprecated in favour of a new native VS Code UI (from v1.59 onwards). Instructions for migrating to the native UI are here:
- https://github.com/microsoft/vscode-docs/blob/vnext/api/extension-guides/testing.md#migrating-from-the-test-explorer-ui

----
EDIT from @aeisenberg 

[Based on a discussion](https://github.com/microsoft/vscode-test-adapter-converter/issues/6), I am changing the title and body of this issue since it looks like we don't need to remove the `hbenl.vscode-test-explorer` dependency. We just need to change the way we are using the adapter.

**Comment by aeisenberg** [comment]
Our release process is still failing when trying to publish to openvsx because of this error. The reason is that the test-ui adapter extension is not published to that registry. If we want to be able to publish to openvsx again, we need to drop the dependency on that extension.

I briefly looked into this. This will require a medium-sized rewrite of our test-ui code since there is just enough friction between the old and new APIs to make it more than a simple find and replace.

**Comment by shati-patel** [comment]
(Unassigning myself for now: Since this is a lot more complex and not super-urgent, we can prioritise it appropriately when there's more time!)

**Comment by aeisenberg** [comment]
Note that when this is fixed, we should undo disabling the open-vsx-publish job https://github.com/github/vscode-codeql/pull/1192

**Comment by aeisenberg** [comment]
It looks like we don't need to remove our dependency on `[hbenl.vscode-test-explorer](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer)`. Instead, we have two possible ways forward here (but we need to verify they work):

1. Simply remove the dependency on `ms-vscode.test-adapter-converter` since the `hbenl.vscode-test-explorer` extension depends on `ms-vscode.test-adapter-converter` in marketplace and `hbenl.test-adapter-converter` in open-vsx. This should just work.
2. Change our publish to open-vsx script so that we replace `ms-vscode.test-adapter-converter` with `hbenl.test-adapter-converter` immediately before publishing.

(1) is preferable, but we need to verify that it works before we can remove that dependency.

**Comment by shati-patel** [comment]
> It looks like we don't need to remove our dependency on [`hbenl.vscode-test-explorer`](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer). Instead, [we have two possible ways forward](https://github.com/microsoft/vscode-test-adapter-converter/issues/6) (but we need to verify they work):
> 
> 1. Simply remove the dependency on `ms-vscode.test-adapter-converter` since the `hbenl.vscode-test-explorer` extension depends on `ms-vscode.test-adapter-converter` in marketplace and `hbenl.test-adapter-converter` in open-vsx. This should just work.
> 2. Change our publish to open-vsx script so that we replace `ms-vscode.test-adapter-converter` with `hbenl.test-adapter-converter` immediately before publishing.
> 
> (1) is preferable, but we need to verify that it works before we can remove that dependency.

Thanks for writing this up!

Number (1) is the state we used to be in, but we explicitly added the dependency on `ms-vscode.test-adapter-converter` in https://github.com/github/vscode-codeql/pull/1084, since users were having issues with loading the CodeQL extension if they'd missed the pop-up about installing dependencies.

Perhaps we should just revert that change again?

**Comment by aeisenberg** [comment]
Yes, (1) _used_ to be broken, but it was fixed by the author of the original `hbenl.vscode-test-explorer` (see the comment I linked to above).

I think the steps could be:

1. check out the 1.6.3 tag
2. remove the extra dependency
3. manually publish to open-vsx v1.6.3 
4. if that works, then make the change in main and re-enable open-vsx publishing for future releases
