### ISSUE TITLE
Show Query Directory opens parent folder

### ISSUE THREAD

**Issue by edoardopirovano** [github/vscode-codeql#1204]
The new Show Query Directory dropdown is very useful. However, (at least on my system - Ubuntu 21.10) it opens the parent of the query directory, with the query directory selected. It would be nicer if it opened the actual query directory, since otherwise clicking away from the file browser makes it hard to get back to the right directory.

(Very minor and non-blocking)

**Comment by aeisenberg** [comment]
Unfortunately, I think this is the expected behaviour. If you select a folder in the explorer view, right-click -> Reveal in Finder (or your OS equivalent), you will see that an explorer/finder window is opened and the desired directory is selected, but it is not opened. I don't think there is any way of fixing this.

**Comment by aeisenberg** [comment]
Actually, a simple fix is to focus on a file that is known to be in the directory. The only file that is guaranteed to exist is `timestamp`.
