### ISSUE TITLE
Extension does not follow config file

### ISSUE THREAD

**Issue by Naman-ntc** [github/vscode-codeql#1446]
**Describe the bug**
I have created a config file for codeql in `$HOME/.config/codeql/config` which contains `--search-path /mnt/t-namanjain/Repos/CodeQL/codeql-repo` argument that I want to be used globally. However, vscode-codeql doesn't seem to follow it and I keep on getting the following error

> Referenced pack 'codeql-javascript' was found in multiple locations.`

**Version**
The CodeQL and VS Code version in which the bug occurs:
* CodeQL CLI v2.7.3
* Extension v1.6.9

I expect that the extension should obey this config file.

**Comment by hmakholm** [comment]
The CLI backend commands that the extension use do recognize a `--search-path` option and its global settings.

However, this search path takes precedence _after_ the currently open workspaces in VS Code, by design -- it is meant as a fallback for finding background libraries that you're not editing. So if you have two different copies of the standard `codeql-javascript` library in your workspace, then setting `--search-path` will not help you.

If this does not resolve your situation, can you please help me understand your use case better:
- Are you only getting the error message you quote in the VSCode extension, or also when you use the CLI directly?
- Do you get it just when editing QL source files, or only when you execute a query?
- Do be completely sure we know what we're speaking of, can you show a screenshot of the context that the error message appears in in the UI?
- What happens if you _don't_ set up the global config file? That is, which porblem are you aiming to solve by having it?
- Which `qlpack.yml` files does your VSCode workspace contain?
- Is the directory you're pointing the `--search-path` at inside the workspace?

**Comment by Naman-ntc** [comment]
Thanks for the prompt response. Answers to your questions below

> Are you only getting the error message you quote in the VSCode extension, or also when you use the CLI directly?
I am getting errors only in the VSCode extension

> Do you get it just when editing QL source files, or only when you execute a query?
I get errors during both editing QL source files and quick evaluation.

> Do be completely sure we know what we're speaking of, can you show a screenshot of the context that the error message appears in in the UI?
I get the error message `Referenced pack 'codeql-javascript' was found in multiple locations` followed by a bunch of paths to qlpacks named `codeql-javascript` in the VSCode workspace

> What happens if you don't set up the global config file? That is, which problem are you aiming to solve by having it?
I am running CodeQL on a bunch of public GitHub repos which sometimes also contain codeql files (or even copies of repositories). They might contain copies of standard codeql libraries causing conflicts. Thus I use it to point to the CLI about the qlpack it needs to follow

> Which qlpack.yml files does your VSCode workspace contain?
My VSCode workspace contains the codeql github repo containing qlpacks for codeql library. Additionally, it also contains other repositories on which I am running codeql (as described above) which contain copies of codeql libraries.

> Is the directory you're pointing the --search-path at inside the workspace?
Yes

**Comment by hmakholm** [comment]
You seem to have forgotten to attach your screenshot of the error message in its context in the UI.

**Comment by hmakholm** [comment]
Anyway, it sounds like things are working as designed. The CodeQL extension does not promise a smooth user experience if you have several copies of the same pack (or several packs with the same name) in your workspace. If you want to use the extension to support editing of `.ql` files, you need to remove enough workspace folders from the workspace that there's only one copy of each pack in the workspace.

It sounds a bit curious that you have a lot of checkouts added to your workspace, because you're running CodeQL on their _content_. There's no need to have the code you're _analyzing_ open as source folders in VSCode, as far as the CodeQL extension is concerned. You might have additional reasons for this, of course, but it's not a use case we support. Sorry.

**Comment by Naman-ntc** [comment]
Oh, I see. I will try to restructure my workspace and operate so conflicting qlpacks do not arrive. 
Thanks!
