### ISSUE TITLE
Quick evaluation: Column order in query results

### ISSUE THREAD

**Issue by Cornelius-Riemenschneider** [github/vscode-codeql#172]
Hi,

when using Quick Evaluation on a predicate in the VSCode CodeQL editor, the query results window shows the resulting columns not in the order of the predicate parameters.
It seems that the first two parameters are swapped in the query results, and then following parameters are listed in-order.

Using Run Query on a QL file seems to produce in-order results.

**Comment by adityasharad** [comment]
Thanks @Cornelius-Riemenschneider. The columns are currently displayed in the order their variables are encountered by the query compiler, rather than the order they are written by the user, which I agree is misleading. We’ll aim to fix this in the query engine used by the CLI, and let you know when the change is available to the VS Code extension.

**Comment by ginsbach** [comment]
https://git.semmle.com/Semmle/code/pull/36580
