### ISSUE TITLE
Variant Analysis Results don't show results for certain non-standard `select` statements

### ISSUE THREAD

**Issue by Marcono1234** [github/vscode-codeql#2630]
**Describe the bug**
The Variant Analysis Results view does not show any results for certain non-standard `select` statements (for queries without `@kind`), even though the query has results and a local database run does show them.

Maybe closely related to #2629, or even the same underlying issue

**Version**
Extension version
```
CodeQL extension version: 1.8.8 
CodeQL CLI version: 2.14.0 
Platform: win32 x64
```

VS Code version
```
Version: 1.80.1 (user setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
```

**To reproduce**
For each of the sample queries below (yes they literally consist only of a `select` statement), open Quick Query and perform Variant Analysis for them on the top 10 repositories.

- ✔️ Works
    ```codeql
    select "first"
    ```
- ✔️ Works
    ```codeql
    select "first", 1
    ```
- ❌ No results
    ```codeql
    select "first", "second"
    ```

This list is not exhaustive; there might be more cases.

**Expected behavior**
The raw results table should always be shown if there are results.

**Comment by robertbrignull** [comment]
Thank you for raising this. This is a known issue that the variant analysis results view can fail to render results sometimes. I don't believe it's the same underlying issue as https://github.com/github/vscode-codeql/issues/2629 and it's more to do with the column types rather than results being from or not from the source.

We've got a couple of internal issues for this and we're going to look into making this behaviour better in two ways:
- If `@kind` metadata is given then we want to respect it, so in cases like this you could put `@kind table` to get it to render the raw results.
- It shouldn't be as eager to render results as alerts (i.e. problem queries) when the columns don't actually match the right format

**Comment by shati-patel** [comment]
Thanks again for reporting the issue! 

This was fixed by https://github.com/github/codeql-variant-analysis-action/pull/854, so should now be working in the extension.
