### ISSUE TITLE
Keep activating the extension ... bug 

### ISSUE THREAD

**Issue by Sim4n6** [github/vscode-codeql#2821]
**Describe the bug**
The extension keeps on activating the extension for a long time. I then have to Codeql restart the server. I get an unexpected error. From there everything starts working normally.

**Version**
CodeQL extension version: 1.8.12 
CodeQL CLI version: 2.14.5 
Platform: win32 x64

but I installed the codeql-binaries.

**To reproduce**
1. installed CodeQL binaries 
2. vscode extension latest 
3. that is all 

**Expected behavior**
Not taking endless time activating the extension.

**Additional context**
I am available to help and provide more details.

**Comment by Sim4n6** [comment]
HEre is a quick recording ... 

[Windows PowerShell 2023-09-15 11-55-33.zip](https://github.com/github/vscode-codeql/files/12618637/Windows.PowerShell.2023-09-15.11-55-33.zip)

**Comment by robertbrignull** [comment]
Hello, I'm sorry you're encountering problems. Could you confirm you're having problems with the CodeQL for Visual Studio Code extension?

> HEre is a quick recording ...

Thanks for including the recording. Is that powershell terminal being provided by the VS Code extension? Unfortunately I'm having trouble understanding the error being demonstrated because the terminal doesn't show any activity.

> The extension keeps on activating the extension for a long time.

Do you have any CodeQL databases registered in the VS Code extension? What sort of size are they? We have seen issues with long startup times when the extension has to index the contents of large databases, and this can be especially slow on windows due to overall slower filesystem access.

> I get an unexpected error

Could you please include what this error is? That'll help us to diagnose what might be happening.

**Comment by Sim4n6** [comment]
> Could you confirm you're having problems with the CodeQL for Visual Studio Code extension?

Yes

> Thanks for including the recording. Is that powershell terminal being provided by the VS Code extension? Unfortunately I'm having trouble understanding the error being demonstrated because the terminal doesn't show any activity.

The bug got no link to me opening Powershell during the recording.

> Do you have any CodeQL databases registered in the VS Code extension? What sort of size are they? We have seen issues with long startup times when the extension has to index the contents of large databases, and this can be especially slow on windows due to overall slower filesystem access.

I have at least 10 Go & Python CodeQL databases loaded on that workspace. 

> Could you please include what this error is? That'll help us to diagnose what might be happening.

I don't remember sorry and now cant reproduce. It was like after I wait the 4min (like in the recording) I CTRL+SHIFT+P and CodeQL restart server. I get the `unexpected error Server has restarted` (something like this). 

I think the problem was somehow linked to the way I used CodeQL. It installed CodeQL into my machine (Win11) and I pointed the **codeql.exe** in VScode settings. When I switched to CodeQl handled through VS Code CodeQl Extension I waited less ... and it works now.

**Comment by robertbrignull** [comment]
> When I switched to CodeQl handled through VS Code CodeQl Extension I waited less ... and it works now.

I'm glad to hear it's working better now 🎉 

> I have at least 10 Go & Python CodeQL databases loaded on that workspace.

The slowness is likely coming from the number of CodeQL databases. If there are some that you don't need any more then deleting them will speed things up. We're also working on changes in the extension that'll help with this so startup time won't be affected by the number of databases. Those changes may take a little while to arrive but they should help.

I'm tempted to close this issue because we think we've found the problem and a workaround, and the symptoms have gone away for you at least for now. If you have more questions or the slowness comes back, please do say.

**Comment by Sim4n6** [comment]
Okey thanks appreciated
