### ISSUE TITLE
Improve database management in the UI

### ISSUE THREAD

**Issue by adityasharad** [github/vscode-codeql#318]
**Is your feature request related to a problem? Please describe.**
- When I have multiple CodeQL databases open in the `Databases` tree view in the workspace, it is difficult to organise them, rename them, or see where they live on the filesystem.
- This is particularly frustrating if I have multiple databases for the same project but different target languages that were all downloaded from an LGTM instance: by default, the name of the database directory is always `projectname_sha`, which makes them impossible to distinguish by language. The current workaround is to remove them from the workspace, rename them on the filesystem, and re-add them.

**Describe the solution you'd like**
- For any database in the workspace, I can navigate to its filesystem location using a command in the right-click or Command Palette menus (similar to `Open Containing Folder` in the Explorer view).
- For any database in the workspace, I can rename or annotate the database name in the UI. (I don't have a strong preference about whether this should also rename the folder on the filesystem.)
- Databases in the UI have a marker telling me the target language.
- I can sort the list of databases in the UI alphabetically or chronologically.

**Describe alternatives you've considered**
Current workaround is manual renaming, which is clunky once the user has already imported the database.

**Additional context**
This is quite a large set of suggestions under a single theme: happy to split it up.

**Comment by aeisenberg** [comment]
All of these suggestions make sense. One comment:

Navigating to a database's location in the file system and renaming the directory outside seems like it would put vscode into a bad state (unless you also remove the database from the workspace first). I think this shouldn't be a recommended option. Though, simply being able to easily navigate to the file system location is useful.

Since github doesn't have the concept of subtasks, it would be useful to split up these tasks. I can take care of it. Thanks for the suggestions.

**Comment by aeisenberg** [comment]
Also, see #322. Sort chronologically by date added or files system creation date, or something else?

**Comment by aeisenberg** [comment]
Closing this issue since I think all portions of it are covered by other issues.
