### ISSUE TITLE
Add a marker of the target language of databases in the tree view

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#321]
This is a subtask of #318.

**Comment by aeisenberg** [comment]
@adityasharad How can I get access to the target language? I see in all of my database directories there is a `refresh` file that contains something like `db-javascript` or `db-cpp`, but I don't know if that's stable enough to trust.

**Comment by adityasharad** [comment]
Good question. There is sadly no fully principled way of doing this, because in theory the CLI and database do not know which language the database is for.

I suggest one of two approaches:
- Look at the name of the `db-<lang>` dataset directory within the database (this is `db.contents.datasetUri`), and maintain a mapping from `<lang>` slugs to the human-readable language names. (The `<lang>` slugs are consistent with the folder names in https://github.com/github/codeql, e.g. C/C++ is always `cpp`.)
- Look at the name of the DB scheme file within the database (this is `db.contents.dbSchemeUri`), and maintain a mapping from DB scheme file names to the human-readable language names. (The DB scheme file names are always `semmlecode.<lang>.dbscheme`, except for Java which is just `semmlecode.dbscheme`.)
