### ISSUE TITLE
Compiler warning overwrites failing test results in test results pane

### ISSUE THREAD

**Issue by rvermeulen** [github/vscode-codeql#3386]
**Describe the bug**

When you execute a QL test from the test explorer, and the compilation of the tested query has warnings, such as unused predicates or deprecated elements, then the diff view of a failed test is not visible.

**Version**
The CodeQL and VS Code version in which the bug occurs.

CodeQL extension version: 1.12.2 
CodeQL CLI version: 2.14.6 
Platform: darwin x64

**To reproduce**

1. Create a failing QL test of a query with an unused predicate or deprecated module.
2. Execute the test

**Expected behavior**

The test explorer shows the diff of the expected and actual output, in addition to the compiler warnings.

**Comment by MathiasVP** [comment]
FWIW, I've also heard Microsoft people mention this before

**Comment by starcke** [comment]
Thanks for the report. I have opened a ticket internally to track this.

**Comment by koesie10** [comment]
This will be fixed in the next release of the extension. Please note that the compiler warning will still show up in the test output as this functionality is used for testing CodeQL itself as well:

![Screenshot 2024-02-28 at 10 48 48](https://github.com/github/vscode-codeql/assets/1112623/4bbe60bd-4e6b-4674-8c09-e87a955450da)
