### ISSUE TITLE
Add ability to download a database from LGTM

### ISSUE THREAD

**Issue by jcreedcmu** [github/vscode-codeql#359]
A possible next step for https://github.com/github/vscode-codeql/issues/357 is to let the user somehow supply an LGTM auth token ato allow downloading snapshots via https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-Snapshots

**Comment by aeisenberg** [comment]
Not sure if this will be helpful, but the github pull request extension handles authentication here: 

https://github.com/microsoft/vscode-pull-request-github/blob/b3995a2c6ba85fa4f31e37035a7a6d4cb4f20c77/src/github/credentials.ts#L169

**Comment by aeisenberg** [comment]
Also, see https://github.com/microsoft/vscode/issues/68738

**Comment by aeisenberg** [comment]
Implementing this is likely to be messy since VS Code does not expose any general authentication mechanism we can use for logging into LGTM. @sj suggested that it might be possible to make changes to LGTM so that downloading databases does not require an auth token. I will discuss with the LGTM team to see if this is possible.

**Comment by aeisenberg** [comment]
Unauthorized db downloads are available in LGTM now. 

Since it looks like there is no easy way for a user to get a fully formed download URL, the extension will have to generate one. Here are the steps:

1. User invokes command "Download DB from LGTM"
2. User pastes in a project link like https://lgtm.com/projects/g/jasmine/jasmine
3. Extension extracts the final 3 path segments and issues a call to https://lgtm.com/api/v1.0/projects/g/jasmine/jasmine
4. Extension extracts the list of available from the result and presents a list of available databases to download
5. User selects language choice
7. Extension creates a complete link based on the language choice and the project ID that is retrieved from step 4
8. Extension downloads and unzips the database as in other commands.

This should be a separate command and separate button. We should possibly consider removing the old download database command from the databases view since this command is one that i expect to be much more useful.

**Comment by aeisenberg** [comment]
Fixed via #405.
