### ISSUE TITLE
Improve library upgrade experience from within the extension

### ISSUE THREAD

**Issue by jcreedcmu** [github/vscode-codeql#388]
The general theme is that we could in principle gather enough information to determine that a user's workspace is using an older version of the codeql library. ('older' could mean 'older than master' or 'older than the current lgtm version'), and suggest upgrades. 

Some reasonable questions surrounding this are:
- should we attempt to do this for all workspaces, or just the vscode-starter-workspace?
- should we be doing this at all, or are there downsides to too aggressive updating?
- how should we do git operations? shelling out to the commandline, braving platform incompatibility and the possibility the user doesn't have git installed at all? including a git node module? some other mechanism for determining version differences?

**Comment by adityasharad** [comment]
Some thoughts in this area:

> should we attempt to do this for all workspaces, or just the vscode-starter-workspace?

I think it is very hard to make this generalise to all workspaces. You don't want to force a user to update from upstream while they have work in progress.

> should we be doing this at all, or are there downsides to too aggressive updating?

We have been gradually moving towards "ask the user before updating or changing the workspace" and I encourage continuing this.

> how should we do git operations?

Can we call into the Git integration/commands included in VS Code?

Concretely for the starter repo, note that there are two possibly update operations:
- `git fetch` the latest commit for the starter repo
- `git submodule update (--remote)` to pull from the latest version of the submodule

**Comment by dbartol** [comment]
Are we worried about upgrading for users who are working on queries to submit to `github/codeql`, users who are writing their own queries and merely consuming our standard libraries, or both?

**Comment by aeisenberg** [comment]
I think this would be a good thing to have. My bias would be towards making this work only in the starter workspace (at first, anyway). Resons:

* Users of this workspace tend to be less experienced with QL and would be less likely to know to upgrade their install at all.
* It's easier to do it for a single, well-known workspace than to try to generalize it across _any_ workspace that might have QL checked out (though, it's certainly something to consider if and when the initial feature is working)
* Starter workspace users would be more likely to only consume standard libraries, making it less likely that there will be conflicts on upgrade (I think this addresses @dbartol's question)
* Also, we won't need to generalize to all kinds of workspaces, addressing @adityasharad's concern.

> Can we call into the Git integration/commands included in VS Code?

No, because these operations are not publicly accessible. There may be a hack we can use, but it's not guaranteed to work long term. I'm also more generally concerned about sticking to public APIs in vscode than in Eclipse because vscode is much more aggressive about updating without explicitly asking the user.

In general, I think it's safer to only upgrade to LGTM-based releases. I'd imagine the workflow would look something like:

1. if the workspace looks like it is the starter workspace
2. periodically run `git fetch` in the background to get the latest tags
3. check for tags that match a certain pattern that indicates they are LGTM tags
4. Ask the user if they want to update to the latest release
5. If yes, then run the git commands to do that.

A bunch of caveats here, like step 2 failing silently if git isn't available. And what to do in step 5 if updating would cause conflicts. We'd also need at least one new user preference for disabling this feature altogether.

**Comment by jcreedcmu** [comment]
> I think it is very hard to make this generalise to all workspaces. You don't want to force a user to update from upstream while they have work in progress.
...
> We have been gradually moving towards "ask the user before updating or changing the workspace" and I encourage continuing this.

Certainly agree that we should not be silently doing any modification to the user's workspace; I'm trying to consider that it might even be annoying to too aggressively *suggest* upgrades.

**Comment by aeisenberg** [comment]
Maybe we only need to check if an upgrade is available after a restart.

**Comment by dbartol** [comment]
I'm worried that we're about to go too far in a direction that diverges from our long-term ideas about how to distribute and consume CodeQL libraries. In the glorious future (tentatively scheduled for December, 2020), here's what I expect a new user to have to do to get started writing a new CodeQL query, expressed as CLI commands:

```bash
codeql pack init --language java
```
This creates a new qlpack.yml in the workspace, and automatically add dependencies to the standard QL library for Java.

```bash
codeql pack update
```
This installs the appropriate versions of the packages that were referenced in `qlpack.yml`

```bash
code Hello.ql
```
They write the query

```bash
codeql query run Hello.ql --database somedatabase
```
They run the query

Messing with users' Git repos seems scary, and shouldn't be necessary once we're in a better place with a package manager. What can we do today that will help users while working towards our package management solution? If we can't think of a stepping stone in that direction, then what's the smallest amount of work that we can do today to guide users to update their libraries?

**Comment by adityasharad** [comment]
Having an out-of-date starter workspace is a fairly common problem for customers and users today. I think a lightweight reminder and command to upgrade to the latest version would be an improvement in that direction, without affecting our ability to provide a long-term packaging solution.
