### ISSUE TITLE
VsCode Error on updating CodeQL 1.2.1

### ISSUE THREAD

**Issue by saikatG** [github/vscode-codeql#419]
**Describe the bug**
When I try to upgrade codeql from vscode, I get the following error: "Unable to check for updates to CodeQL CLI. Error: Release had an unexpected number of assets"

Any ideas why this is happening?

**To Reproduce**
Using command "Codeql: Check for CLI Updates"

Please let me know if you need any other info.

**Comment by aeisenberg** [comment]
Thanks for bringing this up. Looks like this release includes 4 assets (one for each OS and one generic asset). Previous releases only had a single asset. The extension expects only a single asset and fails with the message above when multiple assets are found.

If you want to use the latest CodeQL binary, for now you need to download it separately and point this VS Code setting to the executable: `codeQL.cli.executablePath`.

@hmakholm Is this change in the way releases are made intentional? We can make a change to the extension so that it always grabs the `codeql.zip`, rather than asserting the number of assets in the release.

**Comment by hmakholm** [comment]
Whoops, sorry! Yes, that was intentional. It didn't occur to me that the extension would be confused by additional assets as long as the one it needed is still called `codeql.zip`.

**Comment by hmakholm** [comment]
As as stop-gap measure, I've published a new "latest" release that has only the `codeql.zip`.
@saikatG, I hope this unblocks you.

**Comment by aeisenberg** [comment]
@hmakholm thanks for the quick turnaround. I’ll fix the extension on Monday.
