### ISSUE TITLE
Add link to documentation when a query returns no results

### ISSUE THREAD

**Issue by aeisenberg** [github/vscode-codeql#551]
New users are often confused why a query is returning no results. In practice, though, there are often a small number of well-known reasons why this happens, and they are all documented.

When a query results page opens and it has no results, we should add a link to documentation that possibly explains why this happened and what to do next.

**Comment by eyskim** [comment]
Hi @aeisenberg, I would like to work on this issue if nobody has picked it up yet.

**Comment by eyskim** [comment]
Hi @aeisenberg, upon investigation of this issue, I believe an appropriate approach would be to render a message with the link to the appropriate documentation if the the number of `resultSet.rows` passed to the `<RawTable />` component in `src/view/raw-results-table.tsx` is 0. 

Then, instead of rendering the list of query results as multiple `<RawTableRow />` components, it would render a `<tr>` element with the empty row message.

For example, a change like this:
![image](https://user-images.githubusercontent.com/42628024/118430302-a978b600-b688-11eb-814a-485da5d08392.png)

Such that if there are no results returned from the query, the `emptyTableRow` element would be rendered in `<RawTable />`'s `<tbody>` instead of the list of `<RawTableRow />`.

Before I can make a PR for this issue, I wanted to ask how specific the link to the documentation should be to the user's query. In other words, should it link to specific parts of the documentation based on the query? Or is it sufficient to point to a general link for all empty query results (for example to https://codeql.github.com/docs/codeql-language-guides/)? Perhaps I can do both in separate PRs.

Thanks, and please let me know if there are other considerations I missed!

**Comment by aeisenberg** [comment]
I think that's a fine approach. For now, you can keep the link generic. https://codeql.github.com/docs/codeql-language-guides/ is good. And we can determine a better link later, possibly we can link to the specific language guide.
