### ISSUE TITLE
Multithreaded results interpretation

### ISSUE THREAD

**Issue by henrymercer** [github/vscode-codeql#764]
**Is your feature request related to a problem? Please describe.**
The extension currently runs results interpretation using a single thread, which can be slow for example when running path queries on large databases.

**Describe the solution you'd like**
Results interpretation should make use of the number of threads specified by the `codeQL.runningQueries.numberOfThreads` setting.

**Comment by aschackmull** [comment]
This doesn't look like it's resolved. I still hit the code path https://github.com/github/semmle-code/blob/main/analysis/src/com/semmle/analysis/model/rules/PathRule.java#L366 according to `jstack` (and it's still quite slow).

**Comment by aeisenberg** [comment]
This feature has not yet been released. Have you tried running a dev build of the extension? Downloading the artifact from here https://github.com/github/vscode-codeql/actions/runs/657174712 would probably work (it does contain some code that has not yet been reviewed, though it's likely safe to use).

Otherwise, I'll probably do a release in the next couple of days and you can wait for that.

**Comment by aschackmull** [comment]
My mistake, I recompiled `codeql` and used that and forgot about the possibility of this fix living in the extension.
